vim.g.mapleader = " "
vim.g.maplocalleader = "_"
local keymap = vim.api.nvim_set_keymap
local opts = { noremap = true, silent = true }
keymap("n", "<leader>n", ":noh<CR>", opts)
keymap("n", "H", "^", opts)
keymap("n", "L", "$", opts)
keymap("v", "H", "^", opts)
keymap("v", "L", "$", opts)
keymap("n", "K", "10k", opts)
keymap("n", "J", "10j", opts)
keymap("n", "<leader>%", ":source %<CR>", opts)
keymap("n", "<C-UP>", ":m-3<CR>", opts)
keymap("n", "<C-DOWN>", ":m+<CR>", opts)
keymap("n", "<C-p>", "<Cmd>Telescope find_files<CR>", opts)
keymap("n", "<C-g>", "<Cmd>Telescope live_grep<CR>", opts)
-- keymap("n", "gh", "gT", opts)
-- keymap("n", "gh", "gt", opts)
keymap("n", "<Tab>", ">>", opts)
keymap("n", "<S-Tab>", "<<", opts)
keymap("v", "<Tab>", ">", opts)
keymap("v", "<S-Tab>", "<", opts)
keymap("i", "<S-Tab>", "<C-d>", opts)
keymap("i", "<Tab>", "<C-t>", opts)
keymap("n", "<C-z>", "u", opts)
keymap("n", "<C-S-z>", "<C-r>", opts)
keymap("i", "<C-q>", "<ESC>", opts)
keymap("n", "<S-CR>", "o<ESC>", opts)
keymap("n", "<C-S-CR>", "O<ESC>", opts)
keymap("i", "<C-h>", "<LEFT>", opts)
keymap("i", "<C-l>", "<RIGHT>", opts)
keymap("i", "<C-j>", "<DOWN>", opts)
keymap("i", "<C-a>", "<ESC>A", opts)
keymap("i", "<C-o>", "<ESC>I", opts)
keymap("i", "<C-k>", "<UP>", opts)
keymap("i", "<C-d>", "<BACKSPACE>", opts)
keymap("i", "<C-e>", "<DEL>", opts)
keymap("i", "<", "<><LEFT>", opts)
keymap("i", "[", "[]<LEFT>", opts)
keymap("i", "(", "()<LEFT>", opts)
keymap("i", "{", "{}<LEFT>", opts)
keymap("i", "'", "''<LEFT>", opts)
keymap("i", '"', '""<LEFT>', opts)
-- keymap("i", '<C-i>', '<ESC>A', opts)
-- keymap("i", '<C-o>', '<ESC>I', opts)
